### ISSUE TITLE
Codacy cleanup

### ISSUE THREAD

**Issue by jgfoster** [Open-Acidification/TankController#111]
Codacy has a number of [suggestions](https://github.com/Open-Acidification/TankController/pull/110/checks?check_run_id=2460706717). This is something that multiple people could work on, though there should be some coordination to avoid overlap (perhaps add a comment saying which file you are editing).

The following issues are present:

- Format of .md files
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - GUI/README.md
- Unused libraries in GUI/TankController.py (fixed by #107) 
- `other/*.rb` — not our code so we won't make changes
- Double quote to prevent globbing and word splitting (fixed by #175)
- src/Devices/EEPROM_TC.cpp#L39
  - Check buffer boundaries if used in a loop including recursive loops (CWE-120, CWE-20). 
- src/Devices/Serial_TC.cpp#L54
  - va_list 'arguments' used before va_start() was called
- src/TankControllerLib.cpp#L40
  - Class 'TankControllerLib' does not have a copy constructor which is recommended
- C-style pointer casting in MainMenu.cpp (fixed by #165)

**Comment by IDzyre** [comment]
See Here for the List

https://github.com/Open-Acidification/TankController/runs/2460706717

**Comment by IDzyre** [comment]
I am going to look at the C style casting in Main Menu -- Cameron

**Comment by jgfoster** [comment]
I believe we have resolved the initial issues.
