### ISSUE TITLE
Build and deploy separate executable

### ISSUE THREAD

**Issue by jgfoster** [Open-Acidification/TankController#169]
The current approach requires a user to download the full source for TankController, download the full Arduino IDE, and use the IDE to compile and install the source. It is very easy (using the IDE) to build an executable that could become part of the release. The process for installing it on the board is a bit more complex (see [here](https://skjoldtech.wordpress.com/2019/05/10/flashing-arduino-hex-file-in-linux-with-avrdude/)), but is something that should be available before we encourage widespread distribution.

**Comment by prestoncarman** [comment]
I think this whole export process could be part of `arduino-cli`. When the CLI compiles sketch, it saves the hex: https://github.com/arduino/Arduino/issues/6931 Now we just need to see about putting that value in some online store.
