### ISSUE TITLE
Temperature calibration doesn't work after first time

### ISSUE THREAD

**Issue by KirtOnthank** [Open-Acidification/TankController#174]
It appears that when we calculate a new temperature offset, we are taking the difference between the temperature with temperature correction applied (rather than the raw, uncalibrated temperature reading) and the true temperature entered by the user. We then apply the correction to the raw, uncalibrated temperature reading.  The first time temperature is calibrated on a device there is no problem, because the temperature correction is 0, and there is no difference between the raw reading and the calibrated reading.  However, after this first calibration, you will consistently calculate the incorrect offset. 
A temporary work around is to first calibrate the temperature to the reading that the device is currently displaying.  This will reset the temperature offset to 0, then you can calibrate as normal.

**Comment by jgfoster** [comment]
Fix submitted in PR #176.
