### ISSUE TITLE
pH data appears to be rounded to hundredths (missing thousandths value)

### ISSUE THREAD

**Issue by KirtOnthank** [Open-Acidification/TankController#178]
While we report pH with three digits after the decimal, the third (thousandths) is always zero, which seems exceedingly unlikely!

**Comment by jgfoster** [comment]
The main menu idle view for the LCD has a test that includes the following:

```
  assertEqual("pH=0.000   8.100", lc->getLines().at(0));
  assertEqual("T=12.23 H 15.75 ", lc->getLines().at(1));
```

The code for `MainMenu::idle()` in `MainMenu.cpp:222-225` includes the following:

```
  char output[17];
  snprintf(output, sizeof(output), "pH=%5.3f   %5.3f", PHProbe::instance()->getPh(),
           PHControl::instance()->getTargetPh());
  LiquidCrystal_TC::instance()->writeLine(output, 0);
```

Could you provide a photo showing the main menu display with only two digits after the decimal point?
