### ISSUE TITLE
Support sine wave pH and temperature

### ISSUE THREAD

**Issue by jgfoster** [Open-Acidification/TankController#218]
While the eventual goal is a completely arbitrary path (see #6), that will require a more sophisticated user interface (the ramp function, #5, is simpler). A useful intermediate step would be just two additional pieces of data (for pH and temperature, so a total of four values), amplitude and frequency, from which  a sine wave could be computed and applied.

**Comment by eucalvo** [comment]
pH feature added with #269.

**Comment by jgfoster** [comment]
We need the same for temperature.

**Comment by jgfoster** [comment]
Thermal feature added with #298.
