### ISSUE TITLE
Print actual tests that fail to stdout in testAndBuild.sh

### ISSUE THREAD

**Issue by pianistrevor** [Open-Acidification/TankController#275]
Right now, test failures can be viewed in output.txt, but the command-line summary only includes how many failures are there. It would be nice to see which tests fail, for convenience; this also makes me ask how specific we can (or should) go: should sub-test failures be included as well?

**Comment by pianistrevor** [comment]
Note: might also investigate including serial output in either output.txt or stdout.

**Comment by jgfoster** [comment]
I hadn't noticed that `output.txt` had something so different from standard output. I tried the following:

```
bundle exec arduino_ci.rb --min-free-space=5960 1> >(tee stdout.txt ) 2> >(tee stderr.txt >&2 )
```

This shows that some of the output is going to stderr. I think it would be helpful to put errors to stderr and success to stdout.

**Comment by pianistrevor** [comment]
I've added a PR to Arduino_CI that will output most things to stdout (with appropriate flush statements). It also does some formatting fixes.

**Comment by pianistrevor** [comment]
Retiring this due to discussion with Ian regarding segfaults and the need to use unit buffering.
