### ISSUE TITLE
Deprecation warning in spell checker

### ISSUE THREAD

**Issue by jgfoster** [Open-Acidification/TankController#281]
The tests now start with the following repeated twice:

```
Calling 'DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. 
Please call 'DidYouMean.correct_error(error_name, spell_checker)' instead.
```

I believe this is related to #264. It would be nice to remove this deprecation warning.

**Comment by pianistrevor** [comment]
I don't see that happening in either the GitHub workflows or my own local ones.
