### ISSUE TITLE
Listing files takes longer than WDT

### ISSUE THREAD

**Issue by jgfoster** [Open-Acidification/TankController#294]
The startup goes into an infinite loop of restarting. I suggest the following: (1) disable the watch-dog timer (WDT) at the beginning of the `start()` method and re-enable it at the end; and, (2) stop showing the file list on startup.

**Comment by pianistrevor** [comment]
Is the method you're referring to `TankController::setup()`? And I don't understand what's causing the infinite loop. Does it have to do with a WDT failsafe?

**Comment by jgfoster** [comment]
Yes, the main `setup()` method (not `start()`!). And, yes, if the printing of the file list takes. more than 8 seconds then the WDT failsafe causes a reboot which starts the entire process over again.

**Comment by pianistrevor** [comment]
Fixed via #299
