### ISSUE TITLE
Connect Unit Tests with GitHub Actions

### ISSUE THREAD

**Issue by prestoncarman** [Open-Acidification/TankController#3]
Dependent on #2

Probably better with support for testing like this example: https://stackoverflow.com/questions/780819/how-can-i-unit-test-arduino-code

Another option would be to move things to libraries where its easier to automate testing.
* https://learn.adafruit.com/the-well-automated-arduino-library

**Comment by jgfoster** [comment]
This is now part of branch 2021.
