### ISSUE TITLE
Testing Fails to Report Error

### ISSUE THREAD

**Issue by Zindran-J** [Open-Acidification/TankController#313]
As seen in #310, a test can fail yet report as a success.

**Comment by pianistrevor** [comment]
This might be an issue with [ArduinoCI](https://github.com/Arduino-CI/arduino_ci), not this code. Might be worth checking the source code on that one.

**Comment by jgfoster** [comment]
Fixed by https://github.com/Arduino-CI/arduino_ci/pull/327.
