### ISSUE TITLE
Reduction in Main Menu idle execution time breaks tests

### ISSUE THREAD

**Issue by pianistrevor** [Open-Acidification/TankController#322]
As you can see in the branch `trevor-main-menu`, this change essentially makes it so the idle screen of Main Menu (which shows the PH and temperature) does not need to update _every_ time through the loop. Though the initial idea was to only update it once a second, this seems like it could be too drastic, so now it updates 5 times a second.

The problem is that this breaks two tests: `MenuTest.cpp` and `PHControlTest.cpp`. These breaks are not necessarily because the device won't function correctly, but that the tests were written with very specific timings.

`PHControlTest.cpp` should be easy enough - just modify the timings for the test that failed (which should be faster by about 6-7 ms).

`MenuTest.cpp` might be a bit tougher. Many of the tests break because the wrong lines are on the LCD. This is evident in the following scenario:
- Switching to the 'View Settings' menu (level 1)
- Checking the prompts (should pass)
- Switching back to level 0 (idle)
- Checking the prompts (**will fail because of the 200 ms delay**)
The solution to this would probably be to reset the `lastDisplayTime` private variable in the `MainMenu` class upon switching to any level after 0, so that upon returning to 0 it will properly update.

**Comment by jgfoster** [comment]
I think we will leave the frequent updates for now...
