### ISSUE TITLE
Don't delete a device's data on device deletion

### ISSUE THREAD

**Issue by 3dCameron** [Open-Acidification/TankController#346]
Data deletion should be handled by the Tank view. In order to accomplish this, a datum should store the device's MAC address in a CharField instead of storing the device as a foreign key. This way, a device can be deleted while a history of its data is retained, and if the device is ever added again, it will still be able to access its old data.

**Comment by jgfoster** [comment]
This applies to the previous generation. Our current web UI has a very different design and we can add new issues as appropriate.
