### ISSUE TITLE
Fix unexpected start_at behavior in load_data_recursive()

### ISSUE THREAD

**Issue by 3dCameron** [Open-Acidification/TankController#347]
If start_at is specified and the corresponding endpoint doesn't exist, the next applicable endpoint will be visited. However, this doesn't cascade for the child endpoints, so they will still be subject to the original constraints specified in start_at. For example, if ['2020', '04', '24', '13', '2'] is specified for start_at, but the device doesn't have data for the month of April ('04'), but does have data for the month of May ('05'), then the function will skip to '05' as expected; however, the child endpoints ('24', '13', and '2') will not be reset to 0, and thus will naively assume that the parent is '04', causing all data prior to the second page of the 13th hour of the 24th of May to be erroneously skipped.

This issue is not likely to affect anything within the constraints of normal use, as 'start_at' will always be derived from the last visited path from the previous refresh, or else will be [0, 0, 0, 0, 0]. However, it would be nice to eventually fix this in case we wanted to, say, allow the user to add a new device and specify an arbitrary start point at which to begin downloading data.

**Comment by jgfoster** [comment]
This applies to the previous generation. Our current web UI has a very different design and we can add new issues as appropriate.
