### ISSUE TITLE
Prevent next_path from regressing

### ISSUE THREAD

**Issue by 3dCameron** [Open-Acidification/TankController#349]
Don't allow next_path to regress to a lower level of specificity, unless that lower level of specificity is greater than the previous value of next_path.

For instance, if next_path is currently "2020/05/31/06", don't let it become "2020/05/31", "2020/05", or "2020", as the next run of load_data() will then parse many endpoints that we already hit. The only time this would be acceptable is if the parent endpoint advances to the next directory (e.g. next_path goes from "2020/05/31/06" to "2020/06").

**Comment by jgfoster** [comment]
This applies to the previous generation. Our current web UI has a very different design and we can add new issues as appropriate.
