### ISSUE TITLE
Log calibration values and slope

### ISSUE THREAD

**Issue by prestoncarman** [Open-Acidification/TankController#359]
Features to consider with calibration

* Show logs
* Reset calibration to defaults
* Assign new set points
* Calibrate

**Comment by jgfoster** [comment]
Log calibration values and slope.

**Comment by jgfoster** [comment]
Simplify this task.

**Comment by je-foster** [comment]
I believe that this issue was resolved in #427 or earlier.
- Each pH calibration value is logged when it is sent to the pH probe.
- After each pH calibration, a slope query is sent to the pH probe. When the pH probe responds, its response is logged as a serial event.
