### ISSUE TITLE
Mobile first design

### ISSUE THREAD

**Issue by prestoncarman** [Open-Acidification/TankController#361]
The primary use cases are through a mobile device.

With the exception of:

* importing time series using csv
* exporting data in csv format

**Comment by jgfoster** [comment]
I think this is mostly making sure that the appropriate functionality works on a small screen. That is, we can still have a web app (no need to build for Android and iOS yet).

**Comment by lydiathiel** [comment]
The current version of the web app seems to work fine for mobile use. There are other changes that could be made to the app to make it more user friendly- like refining the layout of the tank navigation menu, or adding highlighting on hover for file links- but the functionality is currently just as accessible to mobile devices as on a bigger screen. I've included screenshots from my iPhone as examples. 
![IMG_6365](https://github.com/Open-Acidification/TankController/assets/104103077/c830016a-dd71-422e-ab97-20ca8fafdb74)
![IMG_6364](https://github.com/Open-Acidification/TankController/assets/104103077/2e508ac0-0761-435d-b6fd-d389fe3b17c0)
![IMG_6363](https://github.com/Open-Acidification/TankController/assets/104103077/628e4066-0f02-40c2-8807-4b372ec9e977)

**Comment by jgfoster** [comment]
I'm going to close the issue for now. It can be reopened (or replaced) if we want more mobile features.
