### ISSUE TITLE
Create "Use Mock" Button for manual testing

### ISSUE THREAD

**Issue by KaelanWillauer** [Open-Acidification/TankController#363]
Debugging with the mock is done by calling the useMock() function somewhere in the code and redeploying the app.
![image](https://user-images.githubusercontent.com/49886320/172069767-206923cb-51f6-4380-82af-406d41ece89d.png)
It would be better if switching to mock could be done inside the application.
1. Create a button in the app_drawer or home_page.
https://docs.flutter.dev/development/ui/widgets/material
2. Call TcInterface.useMock() from the button.

Eventually this should be a toggle between mock and real. A new function similar to useMock() would need to be created in the  TcInterface class which would change _instance to TcRealInterface().

**Comment by jgfoster** [comment]
We now have some automated tests for the Flutter app, so I'll retire this.
