### ISSUE TITLE
Add ramp function for pH and Temperature setpoints

### ISSUE THREAD

**Issue by KirtOnthank** [Open-Acidification/TankController#5]
When asking for a new pH or temperature, there should be a follow-up question of the number of hours (with tenths) to allow to get to the new value (see "SetTime" for an example of sub-states). The default hours will be zero to provide backwards compatibility. If a non-zero value is entered, then the current time and measured value (not target) will be the starting point for the ramp and the newly-entered target and the current time plus the number of hours (with fraction) will be the ending point. Each target query (typically to control the solenoid, but also to report to the screen, serial, and log) will be calculated based on a linear ramp between the start time/value and the end time/target. 

This will require storing four values: (1) start time (`uint32_t`), (2) start value (`float`), (3) end time (also `uint32_t`), and (4) ending value (`float`) (which is already stored as the existing target so no new storage is required for it). The times could be stored as [seconds since 2000](https://adafruit.github.io/RTClib/html/class_date_time.html#a15a271a5c566550e3feae2b9624430f0) (note that `millis()` is based on (re)start time and rolls over in about 50 days so is not reliable as an end time).

**Comment by prestoncarman** [comment]
@all-contributors please add @KirtOnthank for bugs, code, and ideas

**Comment by jgfoster** [comment]
Two set-points and a time for each (before, during, and after).

**Comment by jgfoster** [comment]
When asking for a new pH or temperature, there will be a follow-up question of the number of minutes to allow to get to the new value. The default minutes will be zero to provide backwards compatibility. If a non-zero value is entered, then the current time and target will be the starting point to the ramp and the newly-entered target and the current time plus the number of minutes will be the ending point. Each target query (typically to control the solenoid, but also to report to the screen, serial, and log) will be calculated based on a linear ramp between the start time/target and the end time/target. This will require storing three new values: start time/target and end time. The existing target will be associated with the end time.

**Comment by eucalvo** [comment]
I believe this is the formula:
currentTarget = startingValue + ((currentTime  - startingTime) * (newTarget - startingValue) / (endTime - startTime))

**Comment by eucalvo** [comment]
I believe these issues have been addressed by #266 and #267. Let me know if you see any issues.
