### ISSUE TITLE
Investigate licenses for included libraries

### ISSUE THREAD

**Issue by jgfoster** [Open-Acidification/TankController#78]
Create `docs/libraries.md` with a list of the external libraries used by TankController (use `scripts/install_libraries.sh` and `.arduino-ci.yml` to build the list). With each library identify the source (GitHub URL), the license, and a brief description of the purpose of the library.

**Comment by prestoncarman** [comment]
Current List of Libraries and Licences

* Arduino-CI -  Apache-2.0 License
* Adafruit_BusIO -  MIT License
* Adafruit_MAX31865 - BSD license
* Ethernet - GNU Lesser General Public License
* LiquidCrystal - LGPL-2.1 License
* RTClib - MIT license
* Keypad - GPL-3.0 License
* Arduino-PID-Library - MIT License
* SD - GPL-3.0 License

**Comment by jgfoster** [comment]
https://codebender.cc/library/Keypad#Keypad.cpp is LGPL 2.1
https://github.com/greiman?tab=repositories has some SD libraries that are MIT licensed

**Comment by jgfoster** [comment]
It turns out that the Keypad library files have an LGPL 2.1 license and with #212 we have switched to a more recent library.
